### ISSUE TITLE
Is the library alive?

### ISSUE THREAD

**Issue by zamazan4ik** [fasterthanlime/rc-zip#19]
Hi!

As far as I see, the library is not maintained anymore. @fasterthanlime do you still maintain this library? Because now the current library state is a little bit unclear.

Thanks in advance!

**Comment by fasterthanlime** [comment]
I haven't looked at it in a long while, that's for sure.

If I magically had time to take care of it again (which I probably won't), the first thing I'd do is look at its design with fresh eyes, considering the advances made in async land since it was first put together. I have no idea if it would still hold up :)
